version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src/:/app
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./src/:/app
  redis:
    container_name: "redis_training"
    build: ./docker/redis
    ports:
      - "63791:6379"
    volumes:
      - ./docker/redis/data:/data
